##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [3.7.1] date: [Thu May 07 19:09:28 CST 2020] 
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# target
######################################
TARGET = led_test

######################################
# building variables
######################################
# debug build?
DEBUG = 1
# optimization
# OPT = -Og
OPT = -O0

#######################################
# paths
#######################################
# Build path
BUILD_DIR = build

######################################
# source
######################################
# C sources
C_SOURCES =  \
app/main.c \
bsw/service/cpu/stm32f4xx_it.c \
bsw/service/cpu/system_stm32f4xx.c \
bsw/mcal/src/misc.c \
bsw/mcal/src/stm32f4xx_adc.c \
bsw/mcal/src/stm32f4xx_can.c \
bsw/mcal/src/stm32f4xx_crc.c \
bsw/mcal/src/stm32f4xx_cryp_aes.c \
bsw/mcal/src/stm32f4xx_cryp_des.c \
bsw/mcal/src/stm32f4xx_cryp_tdes.c \
bsw/mcal/src/stm32f4xx_cryp.c \
bsw/mcal/src/stm32f4xx_dac.c \
bsw/mcal/src/stm32f4xx_dbgmcu.c \
bsw/mcal/src/stm32f4xx_dcmi.c \
bsw/mcal/src/stm32f4xx_dma.c \
bsw/mcal/src/stm32f4xx_dma2d.c \
bsw/mcal/src/stm32f4xx_exti.c \
bsw/mcal/src/stm32f4xx_flash_ramfunc.c \
bsw/mcal/src/stm32f4xx_flash.c \
bsw/mcal/src/stm32f4xx_fsmc.c \
bsw/mcal/src/stm32f4xx_gpio.c \
bsw/mcal/src/stm32f4xx_hash_md5.c \
bsw/mcal/src/stm32f4xx_hash_sha1.c \
bsw/mcal/src/stm32f4xx_hash.c \
bsw/mcal/src/stm32f4xx_i2c.c \
bsw/mcal/src/stm32f4xx_iwdg.c \
bsw/mcal/src/stm32f4xx_ltdc.c \
bsw/mcal/src/stm32f4xx_pwr.c \
bsw/mcal/src/stm32f4xx_rcc.c \
bsw/mcal/src/stm32f4xx_rng.c \
bsw/mcal/src/stm32f4xx_rtc.c \
bsw/mcal/src/stm32f4xx_sai.c \
bsw/mcal/src/stm32f4xx_sdio.c \
bsw/mcal/src/stm32f4xx_spi.c \
bsw/mcal/src/stm32f4xx_syscfg.c \
bsw/mcal/src/stm32f4xx_tim.c \
bsw/mcal/src/stm32f4xx_usart.c \
bsw/mcal/src/stm32f4xx_wwdg.c \
bsw/ECUcal/delay/delay.c \
bsw/ECUcal/sys/sys.c \
bsw/ECUcal/usart/usart.c \
app/led/led.c \
app/task/task.c \
app/pit/pit.c \
bsw/ECUcal/iom/iom.c \
bsw/ECUcal/adm/adm.c \
app/test/test.c \
app/key/key.c \
app/oled/oled.c \

# ASM sources
ASM_SOURCES =  \
bsw/service/cpu/core/startup_stm32f407xx.s \


#######################################
# binaries
#######################################
PREFIX = arm-none-eabi-
# The gcc compiler bin path can be either defined in make command via GCC_PATH variable (> make GCC_PATH=xxx)
# either it can be added to the PATH environment variable.
ifdef GCC_PATH
CC = $(GCC_PATH)/$(PREFIX)gcc
AS = $(GCC_PATH)/$(PREFIX)gcc -x assembler-with-cpp
CP = $(GCC_PATH)/$(PREFIX)objcopy
SZ = $(GCC_PATH)/$(PREFIX)size
else
CC = $(PREFIX)gcc
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size
endif
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S
 
#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m4

# fpu
FPU = -mfpu=fpv4-sp-d16

# float-abi
FLOAT-ABI = -mfloat-abi=hard

# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS = 

# C defines
C_DEFS =  \
-DUSE_STDPERIPH_DRIVER \
-DSTM32F40_41xxx \


# AS includes
AS_INCLUDES = 

# C includes
C_INCLUDES =  \
-Ibsw/service/cpu \
-Ibsw/service/cpu/core \
-Ibsw/mcal/inc \
-Ibsw/ECUcal/sys \
-Ibsw/ECUcal/usart \
-Ibsw/ECUcal/delay \
-Iapp/led \
-Iapp/task \
-Iapp/pit \
-Ibsw/ECUcal/iom \
-Iapp/test \
-Iapp/key \
-Iapp/oled \
-Ibsw/ECUcal/adm \

# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

CFLAGS = $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

ifeq ($(DEBUG), 1)
CFLAGS += -g -gdwarf-2
endif


# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"


#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = STM32F407ZGTx_FLASH.ld

# libraries
LIBS = -lc -lm -lnosys 
LIBDIR = 
LDFLAGS = $(MCU) -specs=nano.specs -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections

# default action: build all
all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin


#######################################
# build the application
#######################################
# list of objects
OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))
# list of ASM program objects
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_SOURCES:.s=.o)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))

$(BUILD_DIR)/%.o: %.c Makefile | $(BUILD_DIR) 
	$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.s Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) Makefile
	$(CC) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(HEX) $< $@
	
$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@	
	
$(BUILD_DIR):
	mkdir $@		

#######################################
# clean up
#######################################
clean:
	-rd /s/q $(BUILD_DIR)


######################################
#-rm -fR $(BUILD_DIR)
  
#######################################
# dependencies
#######################################
-include $(wildcard $(BUILD_DIR)/*.d)

# *** EOF ***
